PUT http://localhost:3003/api/main/users/?username=tester
Content-Type: application/json

{
  "newWordsIDs": ["64405825b9d1e327cc098010", "64405825b9d1e327cc098011"]
}

###
PUT http://localhost:3003/api/main/?username=tester
Content-Type: application/json

{
  "userWords": [
    {"id": "64398f2a97ca5fc7a8a1079f", "userAnswer": "корова"}
  ]
}

###
GET http://localhost:3003/api/main/?username=tester

###
POST http://localhost:3003/api/main/words
Content-Type: application/json

{
  "newWords": [
    {
      "correctWord": "борьба",
      "incorrectWord": "б-рьба",
      "age": 1
    },
    {
      "correctWord": "ботинок",
      "incorrectWord": "б-тинок",
      "age": 2
    }
  ]
}

###
POST http://localhost:3003/api/main/users
Content-Type: application/json

{
  "username": "tester"
}