GET http://localhost:3001/api/genitive

###
POST http://localhost:3001/api/genitive/create
Content-Type: application/json

{
  "newTasks": [
    {
    "initial": "бухгалтер",
    "options": [{
      "word": "бухгалтеры",
      "correct": true
    }, {
      "word": "бухгалтера",
      "correct": false
    }]
  },
  {
    "initial": "инженер",
    "options": [{
      "word": "инженеры",
      "correct": true
    }, {
      "word": "инженера",
      "correct": false
    }]
  },
  {
    "initial": "офицер",
    "options": [{
      "word": "офицеры",
      "correct": true
    }, {
      "word": "офицера",
      "correct": false
    }]
  },
  {
    "initial": "тренер",
    "options": [{
      "word": "тренеры",
      "correct": true
    }, {
      "word": "тренера",
      "correct": false
    }]
  },
  {
    "initial": "лектор",
    "options": [{
      "word": "лекторы",
      "correct": true
    }, {
      "word": "лектора",
      "correct": false
    }]
  },
  {
    "initial": "ректор",
    "options": [{
      "word": "ректоры",
      "correct": true
    }, {
      "word": "ректора",
      "correct": false
    }]
  },
  {
    "initial": "шофер",
    "options": [{
      "word": "шоферы",
      "correct": true
    }, {
      "word": "шофера",
      "correct": false
    }]
  },
  {
    "initial": "конструктор",
    "options": [{
      "word": "конструкторы",
      "correct": true
    }, {
      "word": "конструктора",
      "correct": false
    }]
  },
  {
    "initial": "компьютер",
    "options": [{
      "word": "компьютеры",
      "correct": true
    }, {
      "word": "компьютера",
      "correct": false
    }]
  },
  {
    "initial": "договор",
    "options": [{
      "word": "договоры",
      "correct": true
    }, {
      "word": "договора",
      "correct": false
    }]
  },
  {
    "initial": "торт",
    "options": [{
      "word": "торты",
      "correct": true
    }, {
      "word": "торта",
      "correct": false
    }]
  },
  {
    "initial": "соус",
    "options": [{
      "word": "соусы",
      "correct": true
    }, {
      "word": "соуса",
      "correct": false
    }]
  },
  {
    "initial": "суп",
    "options": [{
      "word": "супы",
      "correct": true
    }, {
      "word": "супа",
      "correct": false
    }]
  },
  {
    "initial": "крем",
    "options": [{
      "word": "кремы",
      "correct": true
    }, {
      "word": "крема",
      "correct": false
    }]
  },
  {
    "initial": "полис",
    "options": [{
      "word": "полисы",
      "correct": true
    }, {
      "word": "полиса",
      "correct": false
    }]
  },
  {
    "initial": "десна",
    "options": [{
      "word": "десны",
      "correct": true
    }, {
      "word": "десна",
      "correct": false
    }]
  },
  {
    "initial": "месяц",
    "options": [{
      "word": "месяцы",
      "correct": true
    }, {
      "word": "месяца",
      "correct": false
    }]
  },
  {
    "initial": "возраст",
    "options": [{
      "word": "возрасты",
      "correct": true
    }, {
      "word": "возраста",
      "correct": false
    }]
  },
  {
    "initial": "госпиталь",
    "options": [{
      "word": "госпитали",
      "correct": true
    }, {
      "word": "госпиталя",
      "correct": false
    }]
  },
  {
    "initial": "профессор",
    "options": [{
      "word": "профессора",
      "correct": true
    }, {
      "word": "профессоры",
      "correct": false
    }]
  },
  {
    "initial": "директор",
    "options": [{
      "word": "директора",
      "correct": true
    }, {
      "word": "директоры",
      "correct": false
    }]
  },
  {
    "initial": "доктор",
    "options": [{
      "word": "доктора",
      "correct": true
    }, {
      "word": "докторы",
      "correct": false
    }]
  },
  {
    "initial": "повар",
    "options": [{
      "word": "повара",
      "correct": true
    }, {
      "word": "повары",
      "correct": false
    }]
  },
  {
    "initial": "сторож",
    "options": [{
      "word": "сторожа",
      "correct": true
    }, {
      "word": "сторожи",
      "correct": false
    }]
  },
  {
    "initial": "паспорт",
    "options": [{
      "word": "паспорта",
      "correct": true
    }, {
      "word": "паспорты",
      "correct": false
    }]
  },
  {
    "initial": "погреб",
    "options": [{
      "word": "погреба",
      "correct": true
    }, {
      "word": "погребы",
      "correct": false
    }]
  },
  {
    "initial": "купол",
    "options": [{
      "word": "купола",
      "correct": true
    }, {
      "word": "куполы",
      "correct": false
    }]
  },
  {
    "initial": "катер",
    "options": [{
      "word": "катера",
      "correct": true
    }, {
      "word": "катеры",
      "correct": false
    }]
  },
  {
    "initial": "веер",
    "options": [{
      "word": "веера",
      "correct": true
    }, {
      "word": "вееры",
      "correct": false
    }]
  },
  {
    "initial": "колокол",
    "options": [{
      "word": "колокола",
      "correct": true
    }, {
      "word": "колоколы",
      "correct": false
    }]
  },
  {
    "initial": "мастер",
    "options": [{
      "word": "мастера",
      "correct": true
    }, {
      "word": "мастеры",
      "correct": false
    }]
  },
  {
    "initial": "номер",
    "options": [{
      "word": "номера",
      "correct": true
    }, {
      "word": "номеры",
      "correct": false
    }]
  },
  {
    "initial": "окорок",
    "options": [{
      "word": "окорока",
      "correct": true
    }, {
      "word": "окороки",
      "correct": false
    }]
  },
  {
    "initial": "сорт",
    "options": [{
      "word": "сорта",
      "correct": true
    }, {
      "word": "сорты",
      "correct": false
    }]
  },
  {
    "initial": "том",
    "options": [{
      "word": "тома",
      "correct": true
    }, {
      "word": "томы",
      "correct": false
    }]
  },
  {
    "initial": "ущелье",
    "options": [{
      "word": "ущелий",
      "correct": true
    }, {
      "word": "ущельев",
      "correct": false
    }]
  },
  {
    "initial": "ожерелье",
    "options": [{
      "word": "ожерелий",
      "correct": true
    }, {
      "word": "ожерельев",
      "correct": false
    }]
  },
  {
    "initial": "оладья",
    "options": [{
      "word": "оладий",
      "correct": true
    }, {
      "word": "оладьев",
      "correct": false
    }]
  },
  {
    "initial": "сандалия",
    "options": [{
      "word": "сандалий",
      "correct": true
    }, {
      "word": "сандалей",
      "correct": false
    }]
  },
  {
    "initial": "запястье",
    "options": [{
      "word": "запястий",
      "correct": true
    }, {
      "word": "запястьев",
      "correct": false
    }]
  },
  {
    "initial": "кушанье",
    "options": [{
      "word": "кушаний",
      "correct": true
    }, {
      "word": "кашаньев",
      "correct": false
    }]
  },
  {
    "initial": "раздумье",
    "options": [{
      "word": "раздумий",
      "correct": true
    }, {
      "word": "раздумьев",
      "correct": false
    }]
  },
  {
    "initial": "увечье",
    "options": [{
      "word": "увечий",
      "correct": true
    }, {
      "word": "увечьев",
      "correct": false
    }]
  },
  {
    "initial": "пособие",
    "options": [{
      "word": "пособий",
      "correct": true
    }, {
      "word": "пособиев",
      "correct": false
    }]
  },
  {
    "initial": "претензия",
    "options": [{
      "word": "претензий",
      "correct": true
    }, {
      "word": "претензиев",
      "correct": false
    }]
  },
  {
    "initial": "устье",
    "options": [{
      "word": "устьев",
      "correct": true
    }, {
      "word": "устий",
      "correct": false
    }]
  },
  {
    "initial": "полено",
    "options": [{
      "word": "поленьев",
      "correct": true
    }, {
      "word": "полений",
      "correct": false
    }]
  },
  {
    "initial": "хлопья",
    "options": [{
      "word": "хлопьев",
      "correct": true
    }, {
      "word": "хлопий",
      "correct": false
    }]
  },
  {
    "initial": "подмастерье",
    "options": [{
      "word": "подмастерьев",
      "correct": true
    }, {
      "word": "подмастерий",
      "correct": false
    }]
  },
  {
    "initial": "платье",
    "options": [{
      "word": "платьев",
      "correct": true
    }, {
      "word": "платий",
      "correct": false
    }]
  },
  {
    "initial": "корень",
    "options": [{
      "word": "кореньев",
      "correct": true
    }, {
      "word": "корений",
      "correct": false
    }]
  },
  {
    "initial": "лохмотья",
    "options": [{
      "word": "лохмотьев",
      "correct": true
    }, {
      "word": "лохмотий",
      "correct": false
    }]
  },
  {
    "initial": "колея",
    "options": [{
      "word": "колей",
      "correct": true
    }, {
      "word": "кольев",
      "correct": false
    }]
  },
  {
    "initial": "скамья",
    "options": [{
      "word": "скамей",
      "correct": true
    }, {
      "word": "скамьей",
      "correct": false
    }]
  },
  {
    "initial": "статья",
    "options": [{
      "word": "статей",
      "correct": true
    }, {
      "word": "статьей",
      "correct": false
    }]
  },
  {
    "initial": "судья",
    "options": [{
      "word": "судей",
      "correct": true
    }, {
      "word": "судьей",
      "correct": false
    }]
  },
  {
    "initial": "ладья",
    "options": [{
      "word": "ладей",
      "correct": true
    }, {
      "word": "ладьей",
      "correct": false
    }]
  },
  {
    "initial": "ружьё",
    "options": [{
      "word": "ружей",
      "correct": true
    }, {
      "word": "ружьев",
      "correct": false
    }]
  },
  {
    "initial": "копьё",
    "options": [{
      "word": "копий",
      "correct": true
    }, {
      "word": "копьев",
      "correct": false
    }]
  },
  {
    "initial": "джинсы",
    "options": [{
      "word": "джинсов",
      "correct": true
    }, {
      "word": "джинс",
      "correct": false
    }]
  },
  {
    "initial": "заморозки",
    "options": [{
      "word": "заморозков",
      "correct": true
    }, {
      "word": "заморозок",
      "correct": false
    }]
  },
  {
    "initial": "консервы",
    "options": [{
      "word": "консервов",
      "correct": true
    }, {
      "word": "консерв",
      "correct": false
    }]
  },
  {
    "initial": "ясли",
    "options": [{
      "word": "яслей",
      "correct": true
    }, {
      "word": "ясель",
      "correct": false
    }]
  },
  {
    "initial": "макароны",
    "options": [{
      "word": "макарон",
      "correct": true
    }, {
      "word": "макаронов",
      "correct": false
    }]
  },
  {
    "initial": "сумерки",
    "options": [{
      "word": "сумерек",
      "correct": true
    }, {
      "word": "сумерков",
      "correct": false
    }]
  },
  {
    "initial": "каникулы",
    "options": [{
      "word": "каникул",
      "correct": true
    }, {
      "word": "каникулов",
      "correct": false
    }]
  },
  {
    "initial": "шпроты",
    "options": [{
      "word": "шпрот",
      "correct": true
    }, {
      "word": "шпротов",
      "correct": false
    }]
  },
  {
    "initial": "ножницы",
    "options": [{
      "word": "ножниц",
      "correct": true
    }, {
      "word": "ножницев",
      "correct": false
    }]
  },
  {
    "initial": "брызги",
    "options": [{
      "word": "брызг",
      "correct": true
    }, {
      "word": "брызгов",
      "correct": false
    }]
  },
  {
    "initial": "ворота",
    "options": [{
      "word": "ворот",
      "correct": true
    }, {
      "word": "воротов",
      "correct": false
    }]
  },
  {
    "initial": "клешня",
    "options": [{
      "word": "клешней",
      "correct": true
    }, {
      "word": "клешен",
      "correct": false
    }]
  },
  {
    "initial": "падеж",
    "options": [{
      "word": "падежей",
      "correct": true
    }, {
      "word": "падежов",
      "correct": false
    }]
  },
  {
    "initial": "свеча",
    "options": [{
      "word": "свечей",
      "correct": true
    }, {
      "word": "свеч",
      "correct": false
    }]
  },
  {
    "initial": "гантель",
    "options": [{
      "word": "гантелей",
      "correct": true
    }, {
      "word": "гантель",
      "correct": false
    }]
  },
  {
    "initial": "ясли",
    "options": [{
      "word": "яслей",
      "correct": true
    }, {
      "word": "ясель",
      "correct": false
    }]
  },
  {
    "initial": "будни",
    "options": [{
      "word": "будней",
      "correct": true
    }, {
      "word": "будень",
      "correct": false
    }]
  },
  {
    "initial": "ратуша",
    "options": [{
      "word": "ратуш",
      "correct": true
    }, {
      "word": "ратушей",
      "correct": false
    }]
  },
  {
    "initial": "ниша",
    "options": [{
      "word": "ниш",
      "correct": true
    }, {
      "word": "нишей",
      "correct": false
    }]
  },
  {
    "initial": "чаша",
    "options": [{
      "word": "чаш",
      "correct": true
    }, {
      "word": "чашей",
      "correct": false
    }]
  },
  {
    "initial": "лыжа",
    "options": [{
      "word": "лыж",
      "correct": true
    }, {
      "word": "лыжей",
      "correct": false
    }]
  },
  {
    "initial": "роща",
    "options": [{
      "word": "рощ",
      "correct": true
    }, {
      "word": "рощей",
      "correct": false
    }]
  },
  {
    "initial": "афиша",
    "options": [{
      "word": "афиш",
      "correct": true
    }, {
      "word": "афишей",
      "correct": false
    }]
  },
  {
    "initial": "задача",
    "options": [{
      "word": "задач",
      "correct": true
    }, {
      "word": "задачей",
      "correct": false
    }]
  },
  {
    "initial": "абрикос",
    "options": [{
      "word": "абрикосов",
      "correct": true
    }, {
      "word": "абрикос",
      "correct": false
    }]
  },
  {
    "initial": "апельсин",
    "options": [{
      "word": "апельсинов",
      "correct": true
    }, {
      "word": "апельсин",
      "correct": false
    }]
  },
  {
    "initial": "помидор",
    "options": [{
      "word": "помидоров",
      "correct": true
    }, {
      "word": "помидор",
      "correct": false
    }]
  },
  {
    "initial": "томат",
    "options": [{
      "word": "томатов",
      "correct": true
    }, {
      "word": "томат",
      "correct": false
    }]
  },
  {
    "initial": "мандарин",
    "options": [{
      "word": "мандаринов",
      "correct": true
    }, {
      "word": "мандарин",
      "correct": false
    }]
  },
  {
    "initial": "яблоко",
    "options": [{
      "word": "яблок",
      "correct": true
    }, {
      "word": "яблоков",
      "correct": false
    }]
  },
  {
    "initial": "груша",
    "options": [{
      "word": "груш",
      "correct": true
    }, {
      "word": "грушей",
      "correct": false
    }]
  },
  {
    "initial": "дыня",
    "options": [{
      "word": "дынь",
      "correct": true
    }, {
      "word": "дыней",
      "correct": false
    }]
  },
  {
    "initial": "калмыки",
    "options": [{
      "word": "калмыков",
      "correct": true
    }, {
      "word": "калмык",
      "correct": false
    }]
  },
  {
    "initial": "арабы",
    "options": [{
      "word": "арабов",
      "correct": true
    }, {
      "word": "араб",
      "correct": false
    }]
  },
  {
    "initial": "киргизы",
    "options": [{
      "word": "киргизов",
      "correct": true
    }, {
      "word": "киргиз",
      "correct": false
    }]
  },
  {
    "initial": "узбеки",
    "options": [{
      "word": "узбеков",
      "correct": true
    }, {
      "word": "узбек",
      "correct": false
    }]
  },
  {
    "initial": "эскимосы",
    "options": [{
      "word": "эскимосов",
      "correct": true
    }, {
      "word": "эскимос",
      "correct": false
    }]
  },
  {
    "initial": "латыши",
    "options": [{
      "word": "латышей",
      "correct": true
    }, {
      "word": "латыш",
      "correct": false
    }]
  },
  {
    "initial": "ингуши",
    "options": [{
      "word": "ингушей",
      "correct": true
    }, {
      "word": "ингуш",
      "correct": false
    }]
  },
  {
    "initial": "армяне",
    "options": [{
      "word": "армян",
      "correct": true
    }, {
      "word": "армяней",
      "correct": false
    }]
  },
  {
    "initial": "англичане",
    "options": [{
      "word": "англичан",
      "correct": true
    }, {
      "word": "англичанов",
      "correct": false
    }]
  },
  {
    "initial": "болгары",
    "options": [{
      "word": "болгар",
      "correct": true
    }, {
      "word": "болгаров",
      "correct": false
    }]
  },
  {
    "initial": "башкиры",
    "options": [{
      "word": "башкир",
      "correct": true
    }, {
      "word": "башкиров",
      "correct": false
    }]
  },
  {
    "initial": "грузины",
    "options": [{
      "word": "грузин",
      "correct": true
    }, {
      "word": "грузинов",
      "correct": false
    }]
  },
  {
    "initial": "осетины",
    "options": [{
      "word": "осетин",
      "correct": true
    }, {
      "word": "осетинов",
      "correct": false
    }]
  },
  {
    "initial": "румыны",
    "options": [{
      "word": "румын",
      "correct": true
    }, {
      "word": "румынов",
      "correct": false
    }]
  },
  {
    "initial": "татары",
    "options": [{
      "word": "татар",
      "correct": true
    }, {
      "word": "татаров",
      "correct": false
    }]
  },
  {
    "initial": "цыгане",
    "options": [{
      "word": "цыган",
      "correct": true
    }, {
      "word": "цыганей",
      "correct": false
    }]
  },
  {
    "initial": "турки",
    "options": [{
      "word": "турок",
      "correct": true
    }, {
      "word": "турков",
      "correct": false
    }]
  },
  {
    "initial": "бедуины",
    "options": [{
      "word": "бедуинов",
      "correct": true
    }, {
      "word": "бедуин",
      "correct": false
    }]
  },
  {
    "initial": "акр",
    "options": [{
      "word": "акров",
      "correct": true
    }, {
      "word": "акр",
      "correct": false
    }]
  },
  {
    "initial": "грамм",
    "options": [{
      "word": "граммов",
      "correct": true
    }, {
      "word": "грамм",
      "correct": false
    }]
  },
  {
    "initial": "гектар",
    "options": [{
      "word": "гектаров",
      "correct": true
    }, {
      "word": "гектар",
      "correct": false
    }]
  },
  {
    "initial": "килограмм",
    "options": [{
      "word": "килограммов",
      "correct": true
    }, {
      "word": "килограмм",
      "correct": false
    }]
  },
  {
    "initial": "ампер",
    "options": [{
      "word": "ампер",
      "correct": true
    }, {
      "word": "амперов",
      "correct": false
    }]
  },
  {
    "initial": "аршин",
    "options": [{
      "word": "аршин",
      "correct": true
    }, {
      "word": "аршинов",
      "correct": false
    }]
  },
  {
    "initial": "ватт",
    "options": [{
      "word": "ватт",
      "correct": true
    }, {
      "word": "ваттов",
      "correct": false
    }]
  },
  {
    "initial": "вольт",
    "options": [{
      "word": "вольт",
      "correct": true
    }, {
      "word": "вольтов",
      "correct": false
    }]
  },
  {
    "initial": "радиан",
    "options": [{
      "word": "радиан",
      "correct": true
    }, {
      "word": "радианов",
      "correct": false
    }]
  },
  {
    "initial": "карат",
    "options": [{
      "word": "карат",
      "correct": true
    }, {
      "word": "каратов",
      "correct": false
    }]
  },
  {
    "initial": "децибел",
    "options": [{
      "word": "децибел",
      "correct": true
    }, {
      "word": "децибелов",
      "correct": false
    }]
  },
  {
    "initial": "бронхи",
    "options": [{
      "word": "бронхов",
      "correct": true
    }, {
      "word": "бронх",
      "correct": false
    }]
  },
  {
    "initial": "гольфы",
    "options": [{
      "word": "гольфов",
      "correct": true
    }, {
      "word": "гольф",
      "correct": false
    }]
  },
  {
    "initial": "носки",
    "options": [{
      "word": "носков",
      "correct": true
    }, {
      "word": "носок",
      "correct": false
    }]
  },
  {
    "initial": "бахилы",
    "options": [{
      "word": "бахил",
      "correct": true
    }, {
      "word": "бахилов",
      "correct": false
    }]
  },
  {
    "initial": "ботинки",
    "options": [{
      "word": "ботинок",
      "correct": true
    }, {
      "word": "ботинков",
      "correct": false
    }]
  },
  {
    "initial": "валенки",
    "options": [{
      "word": "валенок",
      "correct": true
    }, {
      "word": "валенков",
      "correct": false
    }]
  },
  {
    "initial": "бакенбарды",
    "options": [{
      "word": "бакенбард",
      "correct": true
    }, {
      "word": "бакенбардов",
      "correct": false
    }]
  },
  {
    "initial": "кроссовки",
    "options": [{
      "word": "кроссовок",
      "correct": true
    }, {
      "word": "кроссовков",
      "correct": false
    }]
  },
  {
    "initial": "плечи",
    "options": [{
      "word": "плеч",
      "correct": true
    }, {
      "word": "плечей",
      "correct": false
    }]
  },
  {
    "initial": "погоны",
    "options": [{
      "word": "погон",
      "correct": true
    }, {
      "word": "погонов",
      "correct": false
    }]
  },
  {
    "initial": "сапоги",
    "options": [{
      "word": "сапог",
      "correct": true
    }, {
      "word": "сапогов",
      "correct": false
    }]
  },
  {
    "initial": "туфли",
    "options": [{
      "word": "туфель",
      "correct": true
    }, {
      "word": "туфлей",
      "correct": false
    }]
  },
  {
    "initial": "чулки",
    "options": [{
      "word": "чулок",
      "correct": true
    }, {
      "word": "чулков",
      "correct": false
    }]
  },
  {
    "initial": "матрац",
    "options": [{
      "word": "матрацев",
      "correct": true
    }, {
      "word": "матрац",
      "correct": false
    }]
  },
  {
    "initial": "блюдце",
    "options": [{
      "word": "блюдец",
      "correct": true
    }, {
      "word": "блюдцев",
      "correct": false
    }]
  },
  {
    "initial": "полотенце",
    "options": [{
      "word": "полотенец",
      "correct": true
    }, {
      "word": "полотенцев",
      "correct": false
    }]
  },
  {
    "initial": "мозоль",
    "options": [{
      "word": "мозолей",
      "correct": true
    }, {
      "word": "мозоль",
      "correct": false
    }]
  },
  {
    "initial": "рояль",
    "options": [{
      "word": "роялей",
      "correct": true
    }, {
      "word": "роялев",
      "correct": false
    }]
  },
  {
    "initial": "скальпель",
    "options": [{
      "word": "скальпелей",
      "correct": true
    }, {
      "word": "скальпелев",
      "correct": false
    }]
  },
  {
    "initial": "вафля",
    "options": [{
      "word": "вафель",
      "correct": true
    }, {
      "word": "вафлей",
      "correct": false
    }]
  },
  {
    "initial": "сабля",
    "options": [{
      "word": "сабель",
      "correct": true
    }, {
      "word": "саблей",
      "correct": false
    }]
  },
  {
    "initial": "цапля",
    "options": [{
      "word": "цапель",
      "correct": true
    }, {
      "word": "цаплей",
      "correct": false
    }]
  },
  {
    "initial": "яблоня",
    "options": [{
      "word": "яблонь",
      "correct": true
    }, {
      "word": "яблоней",
      "correct": false
    }]
  },
  {
    "initial": "богиня",
    "options": [{
      "word": "богинь",
      "correct": true
    }, {
      "word": "богиней",
      "correct": false
    }]
  },
  {
    "initial": "графиня",
    "options": [{
      "word": "графинь",
      "correct": true
    }, {
      "word": "графиней",
      "correct": false
    }]
  },
  {
    "initial": "барышня",
    "options": [{
      "word": "барышень",
      "correct": true
    }, {
      "word": "барышен",
      "correct": false
    }]
  },
  {
    "initial": "боярышня",
    "options": [{
      "word": "боярышень",
      "correct": true
    }, {
      "word": "боярышен",
      "correct": false
    }]
  },
  {
    "initial": "кухня",
    "options": [{
      "word": "кухонь",
      "correct": true
    }, {
      "word": "кухон",
      "correct": false
    }]
  },
  {
    "initial": "вишня",
    "options": [{
      "word": "вишен",
      "correct": true
    }, {
      "word": "вишень",
      "correct": false
    }]
  },
  {
    "initial": "черешня",
    "options": [{
      "word": "черешен",
      "correct": true
    }, {
      "word": "черешень",
      "correct": false
    }]
  },
  {
    "initial": "басня",
    "options": [{
      "word": "басен",
      "correct": true
    }, {
      "word": "басней",
      "correct": false
    }]
  },
  {
    "initial": "башня",
    "options": [{
      "word": "башен",
      "correct": true
    }, {
      "word": "башень",
      "correct": false
    }]
  },
  {
    "initial": "конюшня",
    "options": [{
      "word": "конюшен",
      "correct": true
    }, {
      "word": "конюшень",
      "correct": false
    }]
  },
  {
    "initial": "деревня",
    "options": [{
      "word": "деревень",
      "correct": true
    }, {
      "word": "деревней",
      "correct": false
    }]
  },
  {
    "initial": "блюдце",
    "options": [{
      "word": "блюдец",
      "correct": true
    }, {
      "word": "блюдцев",
      "correct": false
    }]
  },
  {
    "initial": "зеркальце",
    "options": [{
      "word": "зеркалец",
      "correct": true
    }, {
      "word": "зеркальцев",
      "correct": false
    }]
  },
  {
    "initial": "колодец",
    "options": [{
      "word": "колодцев",
      "correct": true
    }, {
      "word": "колодец",
      "correct": false
    }]
  },
  {
    "initial": "деревце",
    "options": [{
      "word": "деревцев",
      "correct": true
    }, {
      "word": "деревец",
      "correct": false
    }]
  },
  {
    "initial": "оконце",
    "options": [{
      "word": "оконцев",
      "correct": true
    }, {
      "word": "оконец",
      "correct": false
    }]
  },
  {
    "initial": "кружевце",
    "options": [{
      "word": "кружевцев",
      "correct": true
    }, {
      "word": "кружевец",
      "correct": false
    }]
  },
  {
    "initial": "болотце",
    "options": [{
      "word": "болотцев",
      "correct": true
    }, {
      "word": "болотец",
      "correct": false
    }]
  },
  {
    "initial": "солнце",
    "options": [{
      "word": "солнц",
      "correct": true
    }, {
      "word": "солнцев",
      "correct": false
    }]
  }
  ]
}
