GET http://localhost:3001/api/stress/gettask

###
POST http://localhost:3001/api/stress/create
Content-Type: application/json

{
  "newTasks": [
    {
    "options": [{
      "word": "аэропОрты",
      "correct": true
    }, {
      "word": "аэропортЫ",
      "correct": false
    }]
  },
  {
    "options": [{
      "word": "бАнты",
      "correct": true
    }, {
      "word": "бантЫ",
      "correct": false
    }]
  },
  {
    "options": [{
      "word": "бОроду",
      "correct": true
    }, {
      "word": "бородУ",
      "correct": false
    }]
  },
  {
    "options": [{
      "word": "бухгАлтеров",
      "correct": true
    }, {
      "word": "бухгалтерОв",
      "correct": false
    }]
  },
  {
    "options": [{
      "word": "вероисповЕдание",
      "correct": true
    }, {
      "word": "вероисповедАние",
      "correct": false
    }]
  },
  {
    "options": [{
      "word": "водопровОд",
      "correct": true
    }, {
      "word": "водопрОвод",
      "correct": false
    }]
  },
  {
    "options": [{
      "word": "газопровОд",
      "correct": true
    }, {
      "word": "газопрОвод",
      "correct": false
    }]
  },
  {
    "options": [{
      "word": "дешевИзна",
      "correct": true
    }, {
      "word": "дешевизнА",
      "correct": false
    }]
  },
  {
    "options": [{
      "word": "диспансЕр",
      "correct": true
    }, {
      "word": "диспАнсер",
      "correct": false
    }]
  },
  {
    "options": [{
      "word": "докумЕнт",
      "correct": true
    }, {
      "word": "докУмент",
      "correct": false
    }]
  },
  {
    "options": [{
      "word": "досУг",
      "correct": true
    }, {
      "word": "дОсуг",
      "correct": false
    }]
  },
  {
    "options": [{
      "word": "еретИк",
      "correct": true
    }, {
      "word": "ерЕтик",
      "correct": false
    }]
  },
  {
    "options": [{
      "word": "жалюзИ",
      "correct": true
    }, {
      "word": "жАлюзи",
      "correct": false
    }]
  },
  {
    "options": [{
      "word": "Иксы",
      "correct": true
    }, {
      "word": "иксЫ",
      "correct": false
    }]
  },
  {
    "options": [{
      "word": "каталОг",
      "correct": true
    }, {
      "word": "катАлог",
      "correct": false
    }]
  },
  {
    "options": [{
      "word": "квартАл",
      "correct": true
    }, {
      "word": "квАртал",
      "correct": false
    }]
  },
  {
    "options": [{
      "word": "киломЕтр",
      "correct": true
    }, {
      "word": "килОметр",
      "correct": false
    }]
  },
  {
    "options": [{
      "word": "кОнусов",
      "correct": true
    }, {
      "word": "конусОв",
      "correct": false
    }]
  },
  {
    "options": [{
      "word": "крАны",
      "correct": true
    }, {
      "word": "кранЫ",
      "correct": false
    }]
  },
  {
    "options": [{
      "word": "кремЕнь",
      "correct": true
    }, {
      "word": "крЕмень",
      "correct": false
    }]
  },
  {
    "options": [{
      "word": "лЕкторов",
      "correct": true
    }, {
      "word": "лекторОв",
      "correct": false
    }]
  },
  {
    "options": [{
      "word": "лОктя,",
      "correct": true
    }, {
      "word": "локтЯ",
      "correct": false
    }]
  },
  {
    "options": [{
      "word": "мЕстностей",
      "correct": true
    }, {
      "word": "местностЕй",
      "correct": false
    }]
  },
  {
    "options": [{
      "word": "намЕрение",
      "correct": true
    }, {
      "word": "намерЕние",
      "correct": false
    }]
  },
  {
    "options": [{
      "word": "нЕдруг",
      "correct": true
    }, {
      "word": "недрУг",
      "correct": false
    }]
  },
  {
    "options": [{
      "word": "недУг",
      "correct": true
    }, {
      "word": "нЕдуг",
      "correct": false
    }]
  },
  {
    "options": [{
      "word": "некролОг",
      "correct": true
    }, {
      "word": "некрОлог",
      "correct": false
    }]
  },
  {
    "options": [{
      "word": "нефтепровОд",
      "correct": true
    }, {
      "word": "нефтепрОвод",
      "correct": false
    }]
  },
  {
    "options": [{
      "word": "новостЕй",
      "correct": true
    }, {
      "word": "нОвостей",
      "correct": false
    }]
  },
  {
    "options": [{
      "word": "нОгтя",
      "correct": true
    }, {
      "word": "ногтЯ",
      "correct": false
    }]
  },
  {
    "options": [{
      "word": "Отрочество",
      "correct": true
    }, {
      "word": "отрОчество",
      "correct": false
    }]
  },
  {
    "options": [{
      "word": "партЕр",
      "correct": true
    }, {
      "word": "пАртер",
      "correct": false
    }]
  },
  {
    "options": [{
      "word": "придАное",
      "correct": true
    }, {
      "word": "прИданое",
      "correct": false
    }]
  },
  {
    "options": [{
      "word": "призЫв",
      "correct": true
    }, {
      "word": "прИзыв",
      "correct": false
    }]
  },
  {
    "options": [{
      "word": "свЕкла",
      "correct": true
    }, {
      "word": "свеклА",
      "correct": false
    }]
  },
  {
    "options": [{
      "word": "сирОты",
      "correct": true
    }, {
      "word": "сИроты",
      "correct": false
    }]
  },
  {
    "options": [{
      "word": "созЫв",
      "correct": true
    }, {
      "word": "сОзыв",
      "correct": false
    }]
  },
  {
    "options": [{
      "word": "сосредотОчение",
      "correct": true
    }, {
      "word": "сосредоточЕние",
      "correct": false
    }]
  },
  {
    "options": [{
      "word": "срЕдства",
      "correct": true
    }, {
      "word": "средствА",
      "correct": false
    }]
  },
  {
    "options": [{
      "word": "столЯр",
      "correct": true
    }, {
      "word": "стОляр",
      "correct": false
    }]
  },
  {
    "options": [{
      "word": "тОрты",
      "correct": true
    }, {
      "word": "тортЫ",
      "correct": false
    }]
  },
  {
    "options": [{
      "word": "тУфля",
      "correct": true
    }, {
      "word": "туфлЯ",
      "correct": false
    }]
  },
  {
    "options": [{
      "word": "цепОчка",
      "correct": true
    }, {
      "word": "цЕпочка",
      "correct": false
    }]
  },
  {
    "options": [{
      "word": "шАрфы",
      "correct": true
    }, {
      "word": "шарфЫ",
      "correct": false
    }]
  },
  {
    "options": [{
      "word": "шофЕр",
      "correct": true
    }, {
      "word": "шОфер",
      "correct": false
    }]
  },
  {
    "options": [{
      "word": "вернА",
      "correct": true
    }, {
      "word": "вЕрна",
      "correct": false
    }]
  },
  {
    "options": [{
      "word": "красИвее",
      "correct": true
    }, {
      "word": "красивЕе",
      "correct": false
    }]
  },
  {
    "options": [{
      "word": "кУхонный",
      "correct": true
    }, {
      "word": "кухОнный",
      "correct": false
    }]
  },
  {
    "options": [{
      "word": "ловкА",
      "correct": true
    }, {
      "word": "лОвка",
      "correct": false
    }]
  },
  {
    "options": [{
      "word": "мозаИчный",
      "correct": true
    }, {
      "word": "мозАичный",
      "correct": false
    }]
  },
  {
    "options": [{
      "word": "оптОвый",
      "correct": true
    }, {
      "word": "Оптовый",
      "correct": false
    }]
  },
  {
    "options": [{
      "word": "прозорлИвый",
      "correct": true
    }, {
      "word": "прозОрливый",
      "correct": false
    }]
  },
  {
    "options": [{
      "word": "слИвовый",
      "correct": true
    }, {
      "word": "сливОвый",
      "correct": false
    }]
  },
  {
    "options": [{
      "word": "бралА",
      "correct": true
    }, {
      "word": "брАла",
      "correct": false
    }]
  },
  {
    "options": [{
      "word": "бралАсь",
      "correct": true
    }, {
      "word": "брАлась",
      "correct": false
    }]
  },
  {
    "options": [{
      "word": "взялА",
      "correct": true
    }, {
      "word": "взЯла",
      "correct": false
    }]
  },
  {
    "options": [{
      "word": "взялАсь",
      "correct": true
    }, {
      "word": "взЯлась",
      "correct": false
    }]
  },
  {
    "options": [{
      "word": "влилАсь",
      "correct": true
    }, {
      "word": "влИлась",
      "correct": false
    }]
  },
  {
    "options": [{
      "word": "ворвалАсь",
      "correct": true
    }, {
      "word": "ворвАлась",
      "correct": false
    }]
  },
  {
    "options": [{
      "word": "воспринЯть",
      "correct": true
    }, {
      "word": "воспрИнять",
      "correct": false
    }]
  },
  {
    "options": [{
      "word": "воспринялА",
      "correct": true
    }, {
      "word": "воспрИняла",
      "correct": false
    }]
  },
  {
    "options": [{
      "word": "воссоздалА",
      "correct": true
    }, {
      "word": "воссоздАла",
      "correct": false
    }]
  },
  {
    "options": [{
      "word": "вручИт",
      "correct": true
    }, {
      "word": "врУчит",
      "correct": false
    }]
  },
  {
    "options": [{
      "word": "гналА",
      "correct": true
    }, {
      "word": "гнАла",
      "correct": false
    }]
  },
  {
    "options": [{
      "word": "гналАсь",
      "correct": true
    }, {
      "word": "гнАлась",
      "correct": false
    }]
  },
  {
    "options": [{
      "word": "добралА",
      "correct": true
    }, {
      "word": "добрАла",
      "correct": false
    }]
  },
  {
    "options": [{
      "word": "добралАсь",
      "correct": true
    }, {
      "word": "добрАлась",
      "correct": false
    }]
  },
  {
    "options": [{
      "word": "дождалАсь",
      "correct": true
    }, {
      "word": "дождАлась",
      "correct": false
    }]
  },
  {
    "options": [{
      "word": "дозвонИтся",
      "correct": true
    }, {
      "word": "дозвОнится",
      "correct": false
    }]
  },
  {
    "options": [{
      "word": "дозИровать",
      "correct": true
    }, {
      "word": "дозировАть",
      "correct": false
    }]
  },
  {
    "options": [{
      "word": "ждалА",
      "correct": true
    }, {
      "word": "ждАла",
      "correct": false
    }]
  },
  {
    "options": [{
      "word": "жилОсь",
      "correct": true
    }, {
      "word": "жИлось",
      "correct": false
    }]
  },
  {
    "options": [{
      "word": "закУпорить",
      "correct": true
    }, {
      "word": "закупОрить",
      "correct": false
    }]
  },
  {
    "options": [{
      "word": "зАнял",
      "correct": true
    }, {
      "word": "занЯл",
      "correct": false
    }]
  },
  {
    "options": [{
      "word": "занялА",
      "correct": true
    }, {
      "word": "зАняла",
      "correct": false
    }]
  },
  {
    "options": [{
      "word": "зАняли",
      "correct": true
    }, {
      "word": "занЯли.",
      "correct": false
    }]
  },
  {
    "options": [{
      "word": "заперлА",
      "correct": true
    }, {
      "word": "зАперла",
      "correct": false
    }]
  },
  {
    "options": [{
      "word": "запломбировАть",
      "correct": true
    }, {
      "word": "запломбИровать",
      "correct": false
    }]
  },
  {
    "options": [{
      "word": "защемИт",
      "correct": true
    }, {
      "word": "защЕмит",
      "correct": false
    }]
  },
  {
    "options": [{
      "word": "звалА",
      "correct": true
    }, {
      "word": "звАла",
      "correct": false
    }]
  },
  {
    "options": [{
      "word": "звонИт",
      "correct": true
    }, {
      "word": "звОнит",
      "correct": false
    }]
  },
  {
    "options": [{
      "word": "кАшлянуть",
      "correct": true
    }, {
      "word": "кашлянУть",
      "correct": false
    }]
  },
  {
    "options": [{
      "word": "клАла",
      "correct": true
    }, {
      "word": "клалА",
      "correct": false
    }]
  },
  {
    "options": [{
      "word": "крАлась",
      "correct": true
    }, {
      "word": "кралАсь",
      "correct": false
    }]
  },
  {
    "options": [{
      "word": "кровоточИть",
      "correct": true
    }, {
      "word": "кровотОчить",
      "correct": false
    }]
  },
  {
    "options": [{
      "word": "лгалА",
      "correct": true
    }, {
      "word": "лгАла",
      "correct": false
    }]
  },
  {
    "options": [{
      "word": "лилА",
      "correct": true
    }, {
      "word": "лИла",
      "correct": false
    }]
  },
  {
    "options": [{
      "word": "лилАсь",
      "correct": true
    }, {
      "word": "лИлась",
      "correct": false
    }]
  },
  {
    "options": [{
      "word": "навралА",
      "correct": true
    }, {
      "word": "наврАла",
      "correct": false
    }]
  },
  {
    "options": [{
      "word": "наделИт",
      "correct": true
    }, {
      "word": "надЕлит",
      "correct": false
    }]
  },
  {
    "options": [{
      "word": "надорвалАсь",
      "correct": true
    }, {
      "word": "надорвАлась",
      "correct": false
    }]
  },
  {
    "options": [{
      "word": "назвалАсь",
      "correct": true
    }, {
      "word": "назвАлась",
      "correct": false
    }]
  },
  {
    "options": [{
      "word": "накренИтся",
      "correct": true
    }, {
      "word": "накрЕнится",
      "correct": false
    }]
  },
  {
    "options": [{
      "word": "налилА",
      "correct": true
    }, {
      "word": "налИла",
      "correct": false
    }]
  },
  {
    "options": [{
      "word": "нарвалА",
      "correct": true
    }, {
      "word": "нарвАла",
      "correct": false
    }]
  },
  {
    "options": [{
      "word": "начАть",
      "correct": true
    }, {
      "word": "нАчать",
      "correct": false
    }]
  },
  {
    "options": [{
      "word": "нАчал",
      "correct": true
    }, {
      "word": "начАл",
      "correct": false
    }]
  },
  {
    "options": [{
      "word": "началА",
      "correct": true
    }, {
      "word": "нАчала",
      "correct": false
    }]
  },
  {
    "options": [{
      "word": "нАчали",
      "correct": true
    }, {
      "word": "начАли",
      "correct": false
    }]
  },
  {
    "options": [{
      "word": "обзвонИт",
      "correct": true
    }, {
      "word": "обзвОнит",
      "correct": false
    }]
  },
  {
    "options": [{
      "word": "облегчИть",
      "correct": true
    }, {
      "word": "облЕгчить",
      "correct": false
    }]
  },
  {
    "options": [{
      "word": "облилАсь",
      "correct": true
    }, {
      "word": "облИлась",
      "correct": false
    }]
  },
  {
    "options": [{
      "word": "обнялАсь",
      "correct": true
    }, {
      "word": "обнЯлась",
      "correct": false
    }]
  },
  {
    "options": [{
      "word": "обогналА",
      "correct": true
    }, {
      "word": "обогнАла",
      "correct": false
    }]
  },
  {
    "options": [{
      "word": "ободралА",
      "correct": true
    }, {
      "word": "ободрАла",
      "correct": false
    }]
  },
  {
    "options": [{
      "word": "ободрИть",
      "correct": true
    }, {
      "word": "обОдрить",
      "correct": false
    }]
  },
  {
    "options": [{
      "word": "ободрИт",
      "correct": true
    }, {
      "word": "обОдрит",
      "correct": false
    }]
  },
  {
    "options": [{
      "word": "ободрИться",
      "correct": true
    }, {
      "word": "обОдриться",
      "correct": false
    }]
  },
  {
    "options": [{
      "word": "ободрИтся",
      "correct": true
    }, {
      "word": "обОдрится",
      "correct": false
    }]
  },
  {
    "options": [{
      "word": "обострИть",
      "correct": true
    }, {
      "word": "обОстрить",
      "correct": false
    }]
  },
  {
    "options": [{
      "word": "одолжИть",
      "correct": true
    }, {
      "word": "одОлжить",
      "correct": false
    }]
  },
  {
    "options": [{
      "word": "одолжИт",
      "correct": true
    }, {
      "word": "одОлжит",
      "correct": false
    }]
  },
  {
    "options": [{
      "word": "озлОбить",
      "correct": true
    }, {
      "word": "озлобИть",
      "correct": false
    }]
  },
  {
    "options": [{
      "word": "окружИт",
      "correct": true
    }, {
      "word": "окрУжит",
      "correct": false
    }]
  },
  {
    "options": [{
      "word": "опОшлить",
      "correct": true
    }, {
      "word": "опошлИть",
      "correct": false
    }]
  },
  {
    "options": [{
      "word": "освЕдомиться",
      "correct": true
    }, {
      "word": "осведомИться",
      "correct": false
    }]
  },
  {
    "options": [{
      "word": "освЕдомится",
      "correct": true
    }, {
      "word": "осведомИтся",
      "correct": false
    }]
  },
  {
    "options": [{
      "word": "отбылА",
      "correct": true
    }, {
      "word": "отбЫла",
      "correct": false
    }]
  },
  {
    "options": [{
      "word": "отдалА",
      "correct": true
    }, {
      "word": "отдАла",
      "correct": false
    }]
  },
  {
    "options": [{
      "word": "откУпорить",
      "correct": true
    }, {
      "word": "откупОрить",
      "correct": false
    }]
  },
  {
    "options": [{
      "word": "отозвалА",
      "correct": true
    }, {
      "word": "отозвАла",
      "correct": false
    }]
  },
  {
    "options": [{
      "word": "отозвалАсь",
      "correct": true
    }, {
      "word": "отозвАлась",
      "correct": false
    }]
  },
  {
    "options": [{
      "word": "перезвонИт",
      "correct": true
    }, {
      "word": "перезвОнит",
      "correct": false
    }]
  },
  {
    "options": [{
      "word": "перелилА",
      "correct": true
    }, {
      "word": "перелИла",
      "correct": false
    }]
  },
  {
    "options": [{
      "word": "плодоносИть",
      "correct": true
    }, {
      "word": "плодонОсить",
      "correct": false
    }]
  },
  {
    "options": [{
      "word": "пломбировАть",
      "correct": true
    }, {
      "word": "пломбИровать",
      "correct": false
    }]
  },
  {
    "options": [{
      "word": "повторИт",
      "correct": true
    }, {
      "word": "повтОрит",
      "correct": false
    }]
  },
  {
    "options": [{
      "word": "позвалА",
      "correct": true
    }, {
      "word": "позвАла",
      "correct": false
    }]
  },
  {
    "options": [{
      "word": "позвонИт",
      "correct": true
    }, {
      "word": "позвОнит",
      "correct": false
    }]
  },
  {
    "options": [{
      "word": "полилА",
      "correct": true
    }, {
      "word": "полИла",
      "correct": false
    }]
  },
  {
    "options": [{
      "word": "понялА",
      "correct": true
    }, {
      "word": "понЯла.",
      "correct": false
    }]
  },
  {
    "options": [{
      "word": "послАла",
      "correct": true
    }, {
      "word": "послалА",
      "correct": false
    }]
  },
  {
    "options": [{
      "word": "прибЫть",
      "correct": true
    }, {
      "word": "прИбыть",
      "correct": false
    }]
  },
  {
    "options": [{
      "word": "прИбыл",
      "correct": true
    }, {
      "word": "прибЫл",
      "correct": false
    }]
  },
  {
    "options": [{
      "word": "прибылА",
      "correct": true
    }, {
      "word": "прИбыла",
      "correct": false
    }]
  },
  {
    "options": [{
      "word": "прИбыли",
      "correct": true
    }, {
      "word": "прибЫли",
      "correct": false
    }]
  },
  {
    "options": [{
      "word": "рвалА",
      "correct": true
    }, {
      "word": "рвАла",
      "correct": false
    }]
  },
  {
    "options": [{
      "word": "сверлИт",
      "correct": true
    }, {
      "word": "свЕрлит",
      "correct": false
    }]
  },
  {
    "options": [{
      "word": "снялА",
      "correct": true
    }, {
      "word": "снЯла",
      "correct": false
    }]
  },
  {
    "options": [{
      "word": "совралА",
      "correct": true
    }, {
      "word": "соврАла",
      "correct": false
    }]
  },
  {
    "options": [{
      "word": "создалА",
      "correct": true
    }, {
      "word": "создАла",
      "correct": false
    }]
  },
  {
    "options": [{
      "word": "сорвалА",
      "correct": true
    }, {
      "word": "сорвАла",
      "correct": false
    }]
  },
  {
    "options": [{
      "word": "сорИт",
      "correct": true
    }, {
      "word": "сОрит",
      "correct": false
    }]
  },
  {
    "options": [{
      "word": "убралА",
      "correct": true
    }, {
      "word": "убрАла",
      "correct": false
    }]
  },
  {
    "options": [{
      "word": "углубИть",
      "correct": true
    }, {
      "word": "углУбить",
      "correct": false
    }]
  },
  {
    "options": [{
      "word": "укрепИт",
      "correct": true
    }, {
      "word": "укрЕпит",
      "correct": false
    }]
  },
  {
    "options": [{
      "word": "чЕрпать",
      "correct": true
    }, {
      "word": "черпАть",
      "correct": false
    }]
  },
  {
    "options": [{
      "word": "щемИт",
      "correct": true
    }, {
      "word": "щЕмит",
      "correct": false
    }]
  },
  {
    "options": [{
      "word": "щЕлкать",
      "correct": true
    }, {
      "word": "щелкАть",
      "correct": false
    }]
  },
  {
    "options": [{
      "word": "довезЕнный",
      "correct": true
    }, {
      "word": "довЕзенный",
      "correct": false
    }]
  },
  {
    "options": [{
      "word": "зАгнутый",
      "correct": true
    }, {
      "word": "загнУтый",
      "correct": false
    }]
  },
  {
    "options": [{
      "word": "зАнятый",
      "correct": true
    }, {
      "word": "занЯтый",
      "correct": false
    }]
  },
  {
    "options": [{
      "word": "занятА",
      "correct": true
    }, {
      "word": "зАнята",
      "correct": false
    }]
  },
  {
    "options": [{
      "word": "зАпертый",
      "correct": true
    }, {
      "word": "запЕртый",
      "correct": false
    }]
  },
  {
    "options": [{
      "word": "заселЁнный",
      "correct": true
    }, {
      "word": "засЕленный",
      "correct": false
    }]
  },
  {
    "options": [{
      "word": "заселенА",
      "correct": true
    }, {
      "word": "засЕлена",
      "correct": false
    }]
  },
  {
    "options": [{
      "word": "кормЯщий",
      "correct": true
    }, {
      "word": "кОрмящий",
      "correct": false
    }]
  },
  {
    "options": [{
      "word": "кровоточАщий",
      "correct": true
    }, {
      "word": "кровотОчащий",
      "correct": false
    }]
  },
  {
    "options": [{
      "word": "нажИвший",
      "correct": true
    }, {
      "word": "нАживший",
      "correct": false
    }]
  },
  {
    "options": [{
      "word": "налИвший",
      "correct": true
    }, {
      "word": "нАливший",
      "correct": false
    }]
  },
  {
    "options": [{
      "word": "нанЯвшийся",
      "correct": true
    }, {
      "word": "нАнявшийся",
      "correct": false
    }]
  },
  {
    "options": [{
      "word": "начАвший",
      "correct": true
    }, {
      "word": "нАчавший",
      "correct": false
    }]
  },
  {
    "options": [{
      "word": "нАчатый",
      "correct": true
    }, {
      "word": "начАтый",
      "correct": false
    }]
  },
  {
    "options": [{
      "word": "низведЕнный",
      "correct": true
    }, {
      "word": "низвЕденный",
      "correct": false
    }]
  },
  {
    "options": [{
      "word": "облегчЕнный",
      "correct": true
    }, {
      "word": "облЕгченный",
      "correct": false
    }]
  },
  {
    "options": [{
      "word": "ободрЕнный",
      "correct": true
    }, {
      "word": "обОдреный",
      "correct": false
    }]
  },
  {
    "options": [{
      "word": "обострЕнный",
      "correct": true
    }, {
      "word": "обОстренный",
      "correct": false
    }]
  },
  {
    "options": [{
      "word": "отключЕнный",
      "correct": true
    }, {
      "word": "отклЮченный",
      "correct": false
    }]
  },
  {
    "options": [{
      "word": "повторЕнный",
      "correct": true
    }, {
      "word": "повтОренный",
      "correct": false
    }]
  },
  {
    "options": [{
      "word": "поделЕнный",
      "correct": true
    }, {
      "word": "подЕленный",
      "correct": false
    }]
  },
  {
    "options": [{
      "word": "понЯвший",
      "correct": true
    }, {
      "word": "пОнявший",
      "correct": false
    }]
  },
  {
    "options": [{
      "word": "прИнятый",
      "correct": true
    }, {
      "word": "принЯтый",
      "correct": false
    }]
  },
  {
    "options": [{
      "word": "принятА",
      "correct": true
    }, {
      "word": "прИнята",
      "correct": false
    }]
  },
  {
    "options": [{
      "word": "приручЕнный",
      "correct": true
    }, {
      "word": "прирУченный",
      "correct": false
    }]
  },
  {
    "options": [{
      "word": "прожИвший",
      "correct": true
    }, {
      "word": "прОживший",
      "correct": false
    }]
  },
  {
    "options": [{
      "word": "снятА",
      "correct": true
    }, {
      "word": "снЯта",
      "correct": false
    }]
  },
  {
    "options": [{
      "word": "сОгнутый",
      "correct": true
    }, {
      "word": "согнУтый",
      "correct": false
    }]
  },
  {
    "options": [{
      "word": "углублЕнный",
      "correct": true
    }, {
      "word": "углУбленный",
      "correct": false
    }]
  },
  {
    "options": [{
      "word": "закУпорив",
      "correct": true
    }, {
      "word": "закупОрив",
      "correct": false
    }]
  },
  {
    "options": [{
      "word": "начАв",
      "correct": true
    }, {
      "word": "нАчав",
      "correct": false
    }]
  },
  {
    "options": [{
      "word": "начАвшись",
      "correct": true
    }, {
      "word": "нАчавшись",
      "correct": false
    }]
  },
  {
    "options": [{
      "word": "отдАв",
      "correct": true
    }, {
      "word": "Отдав",
      "correct": false
    }]
  },
  {
    "options": [{
      "word": "поднЯв",
      "correct": true
    }, {
      "word": "пОдняв",
      "correct": false
    }]
  },
  {
    "options": [{
      "word": "понЯв",
      "correct": true
    }, {
      "word": "пОняв",
      "correct": false
    }]
  },
  {
    "options": [{
      "word": "прибЫв",
      "correct": true
    }, {
      "word": "прИбыв",
      "correct": false
    }]
  },
  {
    "options": [{
      "word": "создАв",
      "correct": true
    }, {
      "word": "сОздав",
      "correct": false
    }]
  },
  {
    "options": [{
      "word": "дОверху",
      "correct": true
    }, {
      "word": "довЕрху",
      "correct": false
    }]
  },
  {
    "options": [{
      "word": "донЕльзя",
      "correct": true
    }, {
      "word": "дОнельзя",
      "correct": false
    }]
  },
  {
    "options": [{
      "word": "дОнизу",
      "correct": true
    }, {
      "word": "донИзу",
      "correct": false
    }]
  },
  {
    "options": [{
      "word": "дОсуха",
      "correct": true
    }, {
      "word": "досУха",
      "correct": false
    }]
  },
  {
    "options": [{
      "word": "зАсветло",
      "correct": true
    }, {
      "word": "засвЕтло",
      "correct": false
    }]
  },
  {
    "options": [{
      "word": "зАтемно",
      "correct": true
    }, {
      "word": "затемнО",
      "correct": false
    }]
  }
  ]
}
